name: Text to Speech - parham

on:
  push:
    paths:
      - text.txt

jobs:
  tts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install gTTS
        run: pip install gTTS

      - name: Convert text to MP3
        run: |
          python - <<EOF
          from gtts import gTTS
          with open("text.txt", "r", encoding="utf-8") as f:
              text = f.read().strip()
          if text:
              voices = {
                  "female": "female.mp3",
                  "male": "male.mp3",
                  "old": "old.mp3",
                  "deep": "deep.mp3"
              }
              for v, filename in voices.items():
                  tts = gTTS(text=text, lang='fa')
                  tts.save(filename)
          EOF

      - name: Commit MP3 files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add *.mp3
          git commit -m "ðŸ”Š ÙØ§ÛŒÙ„ ØµÙˆØªÛŒ Ø¬Ø¯ÛŒØ¯ Ø³Ø§Ø®ØªÙ‡ Ø´Ø¯"
          git push
